
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\Download\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x500")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    208.0,
    437.0,
    fill="#2D2D2D",
    outline="")

canvas.create_rectangle(
    208.0,
    0.0,
    700.0,
    437.0,
    fill="#787575",
    outline="")

canvas.create_rectangle(
    0.0,
    437.0,
    700.0,
    500.0,
    fill="#FF9800",
    outline="")

canvas.create_rectangle(
    208.0,
    408.0,
    700.0,
    437.0,
    fill="#313131",
    outline="")

canvas.create_rectangle(
    81.0,
    441.0,
    112.0,
    487.0,
    fill="#FFFFFF",
    outline="")
image_image_1 = PhotoImage(file=relative_to_assets("Hub.png"))
image_1=canvas.create_image(
    15.0,
    12.0,  
    image = image_image_1
    )

canvas.create_rectangle(
    181.0,
    447.0,
    210.0,
    480.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    32.0,
    446.0,
    61.0,
    479.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    139.0,
    479.0,
    153.0,
    497.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    89.0,
    479.0,
    103.0,
    497.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    238.0,
    477.0,
    252.0,
    499.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    367.0,
    481.0,
    380.0,
    494.0,
    fill="#FFFFFF",
    outline="")
image_image_2=PhotoImage(file=relative_to_assets("Pause Button.png"))
image2=canvas.create_image(
    145,
    460,
    image=image_image_2
   )

canvas.create_text(
    25.0,
    5.0,
    anchor="nw",
    text="HarmonyHub",
    fill="#FFFFFF",
    font=("Inter ExtraBold", 8 * -1)
)

canvas.create_rectangle(
    19.0,
    46.0,
    190.0,
    219.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    208.0,
    0.0,
    700.0,
    46.0,
    fill="#3F3F3F",
    outline="")

canvas.create_rectangle(
    219.0,
    414.0,
    234.0,
    432.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    674.0,
    413.0,
    689.0,
    432.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
